import DeliveryType from "@/types/delivery";

const deliveries: DeliveryType[] = [
  {
    id: 1,
    deliver_at: "2024-10-09 08:00",
    status: "delivered",
    location: "Analakely Antananarivo",
    latitude: -18.91368,
    longitude: 47.53613,
    price: 12000,
    commission: 3000,
    comment:
      "Client très satisfait, demande une nouvelle livraison quand son stock sera épuisé, il nous même donné plus de commission, hehe :)",
    product: {
      id: 1,
      name: "Cartable MSK",
      price: 12000,
      description:
        "A few screens from my ongoing project; List page and filters!",
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 1,
      name: "Tamby Roméo",
      phone_number: "0326798765",
      location: "Analakely Antananarivo",
    },
    delivery_person: {
      id: 1,
      name: "Jean Marc",
      phone_number: "0345467865",
    },
    vehicle: {
      id: 5,
      name: "Moto Honda 1234 TBD",
      type: "moto",
    },
  },
  {
    id: 2,
    deliver_at: "2024-10-10 09:30",
    status: "processing",
    location: "Ambatolampy Antananarivo",
    latitude: -19.3832,
    longitude: 47.4264,
    price: 15000,
    commission: 3500,
    product: {
      id: 2,
      name: "Sac à dos Adidas",
      description:
        "A few screens from my ongoing project; List page and filters!",
      price: 15000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 2,
      name: "Rina Sahondra",
      phone_number: "0346798765",
      location: "Ambatolampy Antananarivo",
    },
    delivery_person: {
      id: 2,
      name: "Patrick Rabe",
      phone_number: "0331234567",
    },
    vehicle: {
      id: 6,
      name: "Camion Toyota 5678 XYZ",
      type: "camion",
    },
  },
  {
    id: 3,
    deliver_at: "2024-10-11 11:30",
    status: "waiting",
    location: "Ivandry Antananarivo",
    latitude: -18.8942,
    longitude: 47.5256,
    price: 10000,
    commission: 2500,
    product: {
      id: 3,
      name: "T-shirt Nike",
      description:
        "A few screens from my ongoing project; List page and filters!",
      price: 10000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 3,
      name: "Aina Fidy",
      phone_number: "0321239876",
      location: "Ivandry Antananarivo",
    },
    delivery_person: {
      id: 3,
      name: "Rakoto Jean",
      phone_number: "0349876543",
    },
    vehicle: {
      id: 7,
      name: "Vélo Trek 4321 ZXC",
      type: "vélo",
    },
  },
  {
    id: 4,
    deliver_at: "2024-10-12 14:30",
    status: "pending",
    location: "Tanjombato Antananarivo",
    latitude: -18.9291,
    longitude: 47.5315,
    price: 18000,
    commission: 4500,
    product: {
      id: 4,
      name: "Chaussures Puma",
      price: 18000,
      description:
        "A few screens from my ongoing project; List page and filters!",
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 4,
      name: "Haja Faniry",
      phone_number: "0337896543",
      location: "Tanjombato Antananarivo",
    },
    delivery_person: {
      id: 4,
      name: "Andry Hery",
      phone_number: "0324567890",
    },
    vehicle: {
      id: 8,
      name: "Scooter Piaggio 8765 DEF",
      type: "scooter",
    },
  },
  {
    id: 5,
    deliver_at: "2024-10-13 18:00",
    status: "canceled",
    location: "Ambohimanarina Antananarivo",
    latitude: -18.8726,
    longitude: 47.5381,
    price: 20000,
    commission: 5000,
    comment:
      "Le client a annulé sa commande à la derniere minute, à cause d’un retard de livraison",
    product: {
      id: 5,
      name: "Casquette Reebok",
      price: 20000,
      description:
        "A few screens from my ongoing project; List page and filters!",
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 5,
      name: "Hoby Rado",
      phone_number: "0343217654",
      location: "Ambohimanarina Antananarivo",
    },
    delivery_person: {
      id: 5,
      name: "Claude Lala",
      phone_number: "0338765432",
    },
    vehicle: {
      id: 9,
      name: "car Renault 1234 ABC",
      type: "car",
    },
  },
  {
    id: 6,
    deliver_at: "2024-10-14 17:00",
    status: "pending",
    location: "Ankadifotsy Antananarivo",
    latitude: -18.9061,
    longitude: 47.5276,
    price: 22000,
    commission: 5500,
    product: {
      id: 6,
      name: "Montre Casio",
      price: 22000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 6,
      name: "Miora Sarah",
      phone_number: "0334567890",
      location: "Ankadifotsy Antananarivo",
    },
    delivery_person: {
      id: 6,
      name: "Faly Richard",
      phone_number: "0346543219",
    },
    vehicle: {
      id: 10,
      name: "Moto Yamaha 9876 GHJ",
      type: "moto",
    },
  },
  {
    id: 7,
    deliver_at: "2024-10-15 17:30",
    status: "waiting",
    location: "Ankorondrano Antananarivo",
    latitude: -18.8924,
    longitude: 47.5238,
    price: 30000,
    commission: 6000,
    product: {
      id: 7,
      name: "Ordinateur Portable HP",
      price: 30000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 7,
      name: "Joelina Hery",
      phone_number: "0329988776",
      location: "Ankorondrano Antananarivo",
    },
    delivery_person: {
      id: 7,
      name: "Mamy Gilbert",
      phone_number: "0347896543",
    },
    vehicle: {
      id: 11,
      name: "car Peugeot 5678 IJK",
      type: "car",
    },
  },
  {
    id: 8,
    deliver_at: "2024-10-16 12:00",
    status: "delivered",
    location: "Ambodivona Antananarivo",
    latitude: -18.9061,
    longitude: 47.5261,
    product: {
      id: 8,
      name: "Chaussures Nike Air",
      price: 17000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 8,
      name: "Lova Kevin",
      phone_number: "0331122334",
      location: "Ambodivona Antananarivo",
    },
    delivery_person: {
      id: 8,
      name: "Fetra Nambinina",
      phone_number: "0328765432",
    },
    vehicle: {
      id: 12,
      name: "Camion Iveco 9876 KLM",
      type: "camion",
    },
  },
  {
    id: 9,
    deliver_at: "2024-10-17 14:30",
    status: "canceled",
    location: "Ampefiloha Antananarivo",
    latitude: -18.9146,
    longitude: 47.5304,
    price: 25000,
    commission: 6250,
    comment:
      "Le client a annulé sa commande à la derniere minute, à cause d’un retard de livraison",
    product: {
      id: 9,
      name: "Lunettes Ray-Ban",
      price: 25000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 9,
      name: "Soa Fitah",
      phone_number: "0342233445",
      location: "Ampefiloha Antananarivo",
    },
    delivery_person: {
      id: 9,
      name: "Feno Micka",
      phone_number: "0334433221",
    },
    vehicle: {
      id: 13,
      name: "Scooter SYM 5432 NOP",
      type: "scooter",
    },
  },
  {
    id: 10,
    deliver_at: "2024-10-18 14:00",
    status: "processing",
    location: "Andraharo Antananarivo",
    latitude: -18.8792,
    longitude: 47.5247,
    price: 19000,
    commission: 4750,
    product: {
      id: 10,
      name: "Casque Bose",
      price: 19000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 10,
      name: "Mandresy Solofonirina",
      phone_number: "0326655443",
      location: "Andraharo Antananarivo",
    },
    delivery_person: {
      id: 10,
      name: "Mbola Hanitra",
      phone_number: "0346677889",
    },
    vehicle: {
      id: 14,
      name: "car Nissan 7654 QRS",
      type: "car",
    },
  },
  {
    id: 11,
    deliver_at: "2024-10-19 15:30",
    status: "pending",
    location: "Antanimena Antananarivo",
    latitude: -18.9054,
    longitude: 47.5298,
    price: 21000,
    commission: 5250,
    product: {
      id: 11,
      name: "Clavier Logitech",
      price: 21000,
    },
    client: {
      id: 11,
      name: "Irina Rakoto",
      phone_number: "0341239876",
      location: "Antanimena Antananarivo",
    },
    delivery_person: {
      id: 11,
      name: "Dina Nono",
      phone_number: "0337766554",
    },
    vehicle: {
      id: 15,
      name: "Vélo Canyon 2345 TUV",
      type: "vélo",
    },
  },
  {
    id: 12,
    deliver_at: "2024-10-20 10:00",
    status: "delivered",
    location: "Anosibe Antananarivo",
    latitude: -18.9134,
    longitude: 47.4954,
    price: 28000,
    commission: 7000,
    product: {
      id: 12,
      name: "Chaise Gamer DXRacer",
      price: 28000,
    },
    client: {
      id: 12,
      name: "Hery Nomena",
      phone_number: "0325566778",
      location: "Anosibe Antananarivo",
    },
    delivery_person: {
      id: 12,
      name: "Rado Lalaina",
      phone_number: "0347890123",
    },
    vehicle: {
      id: 16,
      name: "car BMW 3456 XYZ",
      type: "car",
    },
  },
  {
    id: 13,
    deliver_at: "2024-10-18 10:30",
    status: "waiting",
    location: "Isoraka Antananarivo",
    latitude: -18.9067,
    longitude: 47.5205,
    price: 35000,
    commission: 8750,
    product: {
      id: 13,
      name: "Tablette Samsung",
      price: 35000,
    },
    client: {
      id: 13,
      name: "Faly Haja",
      phone_number: "0338877665",
      location: "Isoraka Antananarivo",
    },
    delivery_person: {
      id: 13,
      name: "Kanto Fetra",
      phone_number: "0349988776",
    },
    vehicle: {
      id: 17,
      name: "Moto Suzuki 6543 WXY",
      type: "moto",
    },
  },
  {
    id: 14,
    deliver_at: "2024-10-22 11:30",
    status: "processing",
    location: "Ambatomaro Antananarivo",
    latitude: -18.8874,
    longitude: 47.5481,
    price: 16000,
    commission: 4000,
    product: {
      id: 14,
      name: "Smartphone iPhone 13",
      price: 16000,
    },
    client: {
      id: 14,
      name: "Dera Liva",
      phone_number: "0323344556",
      location: "Ambatomaro Antananarivo",
    },
    delivery_person: {
      id: 14,
      name: "Tsiry Andry",
      phone_number: "0340987654",
    },
    vehicle: {
      id: 18,
      name: "Camion Mercedes 8765 UVW",
      type: "camion",
    },
  },
  {
    id: 15,
    deliver_at: "2024-10-23 13:00",
    status: "canceled",
    location: "Andoharanofotsy Antananarivo",
    latitude: -19.0086,
    longitude: 47.5435,
    price: 27000,
    commission: 6750,
    comment:
      "Le client a annulé sa commande à la derniere minute, à cause d’un retard de livraison",
    product: {
      id: 15,
      name: "Drone DJI Mavic Air",
      price: 27000,
    },
    client: {
      id: 15,
      name: "Rado Hery",
      phone_number: "0333322110",
      location: "Andoharanofotsy Antananarivo",
    },
    delivery_person: {
      id: 15,
      name: "Ando Jean",
      phone_number: "0325678901",
    },
    vehicle: {
      id: 19,
      name: "car Renault 9876 ABC",
      type: "car",
    },
  },
  {
    id: 16,
    deliver_at: "2024-10-23 12:30",
    status: "canceled",
    location: "Andoharanofotsy Antananarivo",
    latitude: -19.0086,
    longitude: 47.5435,
    price: 27000,
    commission: 6750,
    comment:
      "Le client a annulé sa commande à la derniere minute, à cause d’un retard de livraison",
    product: {
      id: 16,
      name: "Drone DJI Mavic Air",
      price: 27000,
    },
    client: {
      id: 16,
      name: "Rado Hery",
      phone_number: "0333322110",
      location: "Andoharanofotsy Antananarivo",
    },
    delivery_person: {
      id: 16,
      name: "Ando Jean",
      phone_number: "0325678901",
    },
    vehicle: {
      id: 19,
      name: "car Renault 9876 ABC",
      type: "car",
    },
  },
  {
    id: 17,
    deliver_at: "2024-10-24 10:30",
    status: "delivered",
    location: "Ivato Antananarivo",
    latitude: -18.7998,
    longitude: 47.4784,
    price: 30000,
    commission: 7500,
    comment: "La livraison a été effectuée avec succès.",
    product: {
      id: 17,
      name: "Laptop HP Pavilion",
      price: 30000,
    },
    client: {
      id: 17,
      name: "Tiana Ramiarison",
      phone_number: "0341234567",
      location: "Ivato Antananarivo",
    },
    delivery_person: {
      id: 17,
      name: "Nina Raharijaona",
      phone_number: "0323456789",
    },
    vehicle: {
      id: 20,
      name: "van Toyota 1234 XYZ",
      type: "van",
    },
  },
  {
    id: 18,
    deliver_at: "2024-10-25 08:30",
    status: "received_by_delivery_person",
    location: "Antananarivo",
    latitude: -18.8792,
    longitude: 47.5079,
    price: 15000,
    commission: 3750,
    comment: "En attente de confirmation du client.",
    product: {
      id: 18,
      name: "Smartphone Samsung Galaxy",
      price: 15000,
    },
    client: {
      id: 18,
      name: "Miora Andriamialy",
      phone_number: "0334455667",
      location: "Antananarivo",
    },
    delivery_person: {
      id: 18,
      name: "Rija Ravalomanana",
      phone_number: "0324567890",
    },
    vehicle: {
      id: 21,
      name: "motorcycle Yamaha 5678 DEF",
      type: "motorcycle",
    },
  },
  {
    id: 19,
    deliver_at: "2024-10-26 08:00",
    status: "delivered",
    location: "Mahamasina Antananarivo",
    latitude: -18.9111,
    longitude: 47.5296,
    price: 22000,
    commission: 5500,
    comment: "Livraison réussie au client.",
    product: {
      id: 19,
      name: "Camera Canon EOS",
      price: 22000,
    },
    client: {
      id: 19,
      name: "Fidy Andrianjafy",
      phone_number: "0345678901",
      location: "Mahamasina Antananarivo",
    },
    delivery_person: {
      id: 19,
      name: "Tovo Ranjato",
      phone_number: "0326789012",
    },
    vehicle: {
      id: 22,
      name: "truck Ford 9876 GHI",
      type: "truck",
    },
  },
  {
    id: 20,
    deliver_at: "2024-10-27 10:15",
    status: "waiting",
    location: "Antananarivo",
    latitude: -18.8792,
    longitude: 47.5079,
    price: 50000,
    commission: 12500,
    comment: "La livraison est en cours.",
    product: {
      id: 20,
      name: "TV LG 55 inches",
      price: 50000,
    },
    client: {
      id: 20,
      name: "Sitraka Harinjaka",
      phone_number: "0338765432",
      location: "Antananarivo",
    },
    delivery_person: {
      id: 20,
      name: "Bema Ravaloson",
      phone_number: "0327890123",
    },
    vehicle: {
      id: 23,
      name: "car Hyundai 6789 JKL",
      type: "car",
    },
  },
  {
    id: 21,
    deliver_at: "2024-10-28 11:00",
    status: "delivered",
    location: "Andohalo Antananarivo",
    latitude: -18.9265,
    longitude: 47.5233,
    price: 32000,
    commission: 8000,
    comment: "La livraison a été bien reçue.",
    product: {
      id: 21,
      name: "Tablet Apple iPad",
      price: 32000,
    },
    client: {
      id: 21,
      name: "Hery Ravaonjanahary",
      phone_number: "0349876543",
      location: "Andohalo Antananarivo",
    },
    delivery_person: {
      id: 21,
      name: "Tiana Mbola",
      phone_number: "0323456789",
    },
    vehicle: {
      id: 24,
      name: "van Mercedes 1234 OPQ",
      type: "van",
    },
  },
  {
    id: 22,
    deliver_at: "2024-10-29 09:15",
    status: "canceled",
    location: "Ankorondrano Antananarivo",
    latitude: -18.9199,
    longitude: 47.5272,
    price: 19000,
    commission: 4750,
    comment: "La livraison a échoué à cause d'une adresse incorrecte.",
    product: {
      id: 22,
      name: "Smartwatch Fitbit",
      price: 19000,
    },
    client: {
      id: 22,
      name: "Vola Rabemananjara",
      phone_number: "0336543210",
      location: "Ankorondrano Antananarivo",
    },
    delivery_person: {
      id: 22,
      name: "Andry Raketaka",
      phone_number: "0322345678",
    },
    vehicle: {
      id: 25,
      name: "motorcycle Honda 2345 QRS",
      type: "motorcycle",
    },
  },
  {
    id: 23,
    deliver_at: "2024-10-30 10:00",
    status: "delivered",
    location: "Analakely Antananarivo",
    latitude: -18.9265,
    longitude: 47.516,
    price: 35000,
    commission: 8750,
    comment: "Le client était très satisfait de la livraison.",
    product: {
      id: 23,
      name: "Printer Epson EcoTank",
      price: 35000,
    },
    client: {
      id: 23,
      name: "Rosa Andriamifidy",
      phone_number: "0341237890",
      location: "Analakely Antananarivo",
    },
    delivery_person: {
      id: 23,
      name: "Mika Andrianarivo",
      phone_number: "0325432109",
    },
    vehicle: {
      id: 26,
      name: "car Nissan 5432 TUV",
      type: "car",
    },
  },
  {
    id: 24,
    deliver_at: "2024-10-31 15:30",
    status: "received_by_delivery_person",
    location: "Tsaralalana Antananarivo",
    latitude: -18.9262,
    longitude: 47.5163,
    price: 45000,
    commission: 11250,
    comment: "En attente de confirmation du client.",
    product: {
      id: 24,
      name: "Speaker Bose",
      price: 45000,
    },
    client: {
      id: 24,
      name: "Sola Ravoahangy",
      phone_number: "0346789012",
      location: "Tsaralalana Antananarivo",
    },
    delivery_person: {
      id: 24,
      name: "Eliandro Raharijaona",
      phone_number: "0321234567",
    },
    vehicle: {
      id: 27,
      name: "van Fiat 8765 WXY",
      type: "van",
    },
  },
  {
    id: 25,
    deliver_at: "2024-11-01 11:20",
    status: "canceled",
    location: "Behoririka Antananarivo",
    latitude: -18.9265,
    longitude: 47.5133,
    price: 37000,
    commission: 9250,
    comment: "Le client a annulé sa commande à la derniere minute.",
    product: {
      id: 25,
      name: "Headphones Sony WH-1000XM4",
      price: 37000,
    },
    client: {
      id: 25,
      name: "Aina Ranjavola",
      phone_number: "0348765432",
      location: "Behoririka Antananarivo",
    },
    delivery_person: {
      id: 25,
      name: "Kanto Ravanantsoa",
      phone_number: "0324567890",
    },
    vehicle: {
      id: 28,
      name: "motorcycle Suzuki 4321 ABC",
      type: "motorcycle",
    },
  },
  {
    id: 26,
    deliver_at: "2024-10-02 13:30",
    status: "received_by_delivery_person",
    location: "Avaradoha Antananarivo",
    latitude: -18.9222,
    longitude: 47.5108,
    price: 21000,
    commission: 5250,
    comment: "La livraison est en cours.",
    product: {
      id: 26,
      name: "Bluetooth Speaker JBL",
      price: 21000,
    },
    client: {
      id: 26,
      name: "Rija Ramiarison",
      phone_number: "0341112233",
      location: "Avaradoha Antananarivo",
    },
    delivery_person: {
      id: 26,
      name: "Miora Rafaralahy",
      phone_number: "0323456789",
    },
    vehicle: {
      id: 29,
      name: "car Peugeot 1234 UVW",
      type: "car",
    },
  },
  {
    id: 27,
    deliver_at: "2024-11-03 16:15",
    status: "delivered",
    location: "Ankorondrano Antananarivo",
    latitude: -18.9211,
    longitude: 47.5226,
    price: 40000,
    commission: 10000,
    comment: "La livraison a été réussie.",
    product: {
      id: 27,
      name: "Game Console PlayStation 5",
      price: 40000,
    },
    client: {
      id: 27,
      name: "Mila Rakotoarisoa",
      phone_number: "0345678901",
      location: "Ankorondrano Antananarivo",
    },
    delivery_person: {
      id: 27,
      name: "Rina Rasoanaivo",
      phone_number: "0324567890",
    },
    vehicle: {
      id: 30,
      name: "van Renault 6789 STU",
      type: "van",
    },
  },
  {
    id: 28,
    deliver_at: "2024-10-15 09:30",
    status: "pending",
    location: "Ivandry Antananarivo",
    latitude: -18.8996,
    longitude: 47.5375,
    price: 10000,
    commission: 2500,
    comment: "Client est pressé, livraison prioritaire.",
    product: {
      id: 3,
      name: "Cahier 200 pages",
      price: 10000,
      description: "Un cahier de 200 pages de haute qualité.",
      company: {
        id: 2,
        name: "Rivo Stationery",
        phone_number: "034 67 123 45",
      },
    },
    client: {
      id: 2,
      name: "Haja Solofo",
      phone_number: "0331234567",
      location: "Ivandry Antananarivo",
    },
    delivery_person: {
      id: 3,
      name: "Andry Rakoto",
      phone_number: "0341236547",
    },
    vehicle: {
      id: 6,
      name: "Moto Honda 450 CRF",
      type: "moto",
    },
  },
  {
    id: 29,
    deliver_at: "2024-10-14 14:45",
    status: "delivered",
    location: "Ambatoroka Antananarivo",
    latitude: -18.9101,
    longitude: 47.5254,
    price: 8000,
    commission: 2000,
    comment: "Livraison effectuée avec succès.",
    product: {
      id: 4,
      name: "Stylo à bille",
      price: 8000,
      description: "Stylo à bille de couleur bleue.",
      company: {
        id: 3,
        name: "Papeterie Kely",
        phone_number: "032 45 678 90",
      },
    },
    client: {
      id: 3,
      name: "Zo Rasoanaivo",
      phone_number: "0328765432",
      location: "Ambatoroka Antananarivo",
    },
    delivery_person: {
      id: 2,
      name: "Solonirina Rabe",
      phone_number: "0339876543",
    },
    vehicle: {
      id: 7,
      name: "Vélo Giant MTB",
      type: "vélo",
    },
  },
  {
    id: 30,
    deliver_at: "2024-10-16 11:00",
    status: "waiting",
    location: "Isoraka Antananarivo",
    latitude: -18.9107,
    longitude: 47.5285,
    price: 15000,
    commission: 4000,
    comment: "Client veut être appelé 5 minutes avant l'arrivée.",
    product: {
      id: 5,
      name: "Tablette 10 pouces",
      price: 15000,
      description: "Tablette Android avec écran 10 pouces.",
      company: {
        id: 4,
        name: "Tech Solutions",
        phone_number: "033 76 543 21",
      },
    },
    client: {
      id: 4,
      name: "Rado Andriamampianina",
      phone_number: "0346543210",
      location: "Isoraka Antananarivo",
    },
    delivery_person: {
      id: 1,
      name: "Jean Marc",
      phone_number: "0345467865",
    },
    vehicle: {
      id: 5,
      name: "Moto Honda 1234 TBD",
      type: "moto",
    },
  },
  {
    id: 31,
    deliver_at: "2024-10-13 16:20",
    status: "delivered",
    location: "Ampasampito Antananarivo",
    latitude: -18.9034,
    longitude: 47.5291,
    price: 5000,
    commission: 1500,
    comment: "Client a demandé un reçu papier.",
    product: {
      id: 6,
      name: "Livre de poche",
      price: 5000,
      description: "Roman classique format poche.",
      company: {
        id: 5,
        name: "Librairie Tsara",
        phone_number: "034 23 456 78",
      },
    },
    client: {
      id: 5,
      name: "Irinà Rasolo",
      phone_number: "0337654321",
      location: "Ampasampito Antananarivo",
    },
    delivery_person: {
      id: 4,
      name: "Tina Ravelonarivo",
      phone_number: "0349876543",
    },
    vehicle: {
      id: 8,
      name: "Vélo Électrique City Ride",
      type: "vélo",
    },
  },
  {
    id: 32,
    deliver_at: "2024-10-12 10:15",
    status: "canceled",
    location: "Andravoahangy Antananarivo",
    latitude: -18.9046,
    longitude: 47.5312,
    price: 6000,
    commission: 1000,
    comment: "Client a annulé à la dernière minute.",
    product: {
      id: 7,
      name: "Chargeur universel",
      price: 6000,
      description: "Chargeur pour plusieurs types d'appareils.",
      company: {
        id: 6,
        name: "ElecTech",
        phone_number: "032 54 321 09",
      },
    },
    client: {
      id: 6,
      name: "Faly Randrianarisoa",
      phone_number: "0343210987",
      location: "Andravoahangy Antananarivo",
    },
    delivery_person: {
      id: 5,
      name: "Hery Ramiandrisoa",
      phone_number: "0327654321",
    },
    vehicle: {
      id: 6,
      name: "Moto Honda 450 CRF",
      type: "moto",
    },
  },
  {
    id: 33,
    deliver_at: "2024-10-11 18:00",
    status: "delivered",
    location: "67Ha Antananarivo",
    latitude: -18.9089,
    longitude: 47.541,
    price: 14000,
    commission: 3000,
    comment: "Client satisfait, demande de réduction pour prochaine commande.",
    product: {
      id: 8,
      name: "Coffret cadeau",
      price: 14000,
      description: "Coffret cadeau spécial avec divers produits.",
      company: {
        id: 7,
        name: "Boutique Bonheur",
        phone_number: "034 98 765 43",
      },
    },
    client: {
      id: 7,
      name: "Lova Razafy",
      phone_number: "0324567890",
      location: "67Ha Antananarivo",
    },
    delivery_person: {
      id: 6,
      name: "Tsanta Raharison",
      phone_number: "0331234567",
    },
    vehicle: {
      id: 9,
      name: "Voiture Renault Clio",
      type: "voiture",
    },
  },
  {
    id: 34,
    deliver_at: "2024-10-14 12:45",
    status: "waiting",
    location: "Mahamasina Antananarivo",
    latitude: -18.9139,
    longitude: 47.5235,
    price: 9000,
    commission: 2000,
    comment: "Client à contacter pour récupérer un code promo.",
    product: {
      id: 9,
      name: "Parfum Hommes 50ml",
      price: 9000,
      description: "Eau de toilette pour hommes, 50ml.",
      company: {
        id: 8,
        name: "Parfumerie Mandroso",
        phone_number: "034 45 876 90",
      },
    },
    client: {
      id: 8,
      name: "Toky Rasolonirina",
      phone_number: "0348765432",
      location: "Mahamasina Antananarivo",
    },
    delivery_person: {
      id: 7,
      name: "Miora Andrianjafy",
      phone_number: "0345678901",
    },
    vehicle: {
      id: 10,
      name: "Voiture Peugeot 208",
      type: "voiture",
    },
  },
  {
    id: 35,
    deliver_at: "2024-10-10 17:20",
    status: "delivered",
    location: "Ankadifotsy Antananarivo",
    latitude: -18.9056,
    longitude: 47.5303,
    price: 11000,
    commission: 2500,
    comment: "Client satisfait, livraison rapide.",
    product: {
      id: 10,
      name: "Sac à dos étanche",
      price: 11000,
      description: "Sac à dos résistant à l'eau, idéal pour le voyage.",
      company: {
        id: 9,
        name: "Voyage en Sac",
        phone_number: "032 54 678 90",
      },
    },
    client: {
      id: 9,
      name: "Miary Ravelomanana",
      phone_number: "0332345678",
      location: "Ankadifotsy Antananarivo",
    },
    delivery_person: {
      id: 8,
      name: "Manitra Randria",
      phone_number: "0347654321",
    },
    vehicle: {
      id: 6,
      name: "Moto Honda 450 CRF",
      type: "moto",
    },
  },
  {
    id: 36,
    deliver_at: "2024-10-09 08:30",
    status: "pending",
    location: "Ambohipo Antananarivo",
    latitude: -18.9102,
    longitude: 47.5347,
    price: 7000,
    commission: 1800,
    comment: "Client veut une confirmation avant l'arrivée.",
    product: {
      id: 11,
      name: "Gourde 500ml",
      price: 7000,
      description: "Gourde en acier inoxydable 500ml.",
      company: {
        id: 10,
        name: "HydroStyle",
        phone_number: "034 98 123 45",
      },
    },
    client: {
      id: 10,
      name: "Farah Andrianjatovo",
      phone_number: "0322345678",
      location: "Ambohipo Antananarivo",
    },
    delivery_person: {
      id: 9,
      name: "Niry Rajo",
      phone_number: "0348761234",
    },
    vehicle: {
      id: 7,
      name: "Vélo Giant MTB",
      type: "vélo",
    },
  },
  {
    id: 37,
    deliver_at: "2024-10-08 10:00",
    status: "delivered",
    location: "Alarobia Antananarivo",
    latitude: -18.9113,
    longitude: 47.5392,
    price: 12500,
    commission: 3000,
    comment: "Client satisfait de la rapidité de la livraison.",
    product: {
      id: 12,
      name: "Casque audio Bluetooth",
      price: 12500,
      description: "Casque Bluetooth avec son de haute qualité.",
      company: {
        id: 11,
        name: "Tech Gear",
        phone_number: "032 34 567 89",
      },
    },
    client: {
      id: 11,
      name: "Aina Rabearisoa",
      phone_number: "0335671234",
      location: "Alarobia Antananarivo",
    },
    delivery_person: {
      id: 10,
      name: "Tiana Randrianary",
      phone_number: "0345432123",
    },
    vehicle: {
      id: 6,
      name: "Moto Honda 450 CRF",
      type: "moto",
    },
  },
  {
    id: 38,
    deliver_at: "2024-10-07 15:40",
    status: "canceled",
    location: "Anosy Antananarivo",
    latitude: -18.9146,
    longitude: 47.5209,
    price: 9000,
    commission: 1000,
    comment: "Client a annulé en raison d'un changement d'adresse.",
    product: {
      id: 13,
      name: "Bouilloire électrique",
      price: 9000,
      description: "Bouilloire électrique en inox.",
      company: {
        id: 12,
        name: "Cuisine Moderne",
        phone_number: "033 45 876 54",
      },
    },
    client: {
      id: 12,
      name: "Vola Razafindrakoto",
      phone_number: "0345674321",
      location: "Anosy Antananarivo",
    },
    delivery_person: {
      id: 11,
      name: "Eric Rakotomanga",
      phone_number: "0322341234",
    },
    vehicle: {
      id: 9,
      name: "Voiture Renault Clio",
      type: "voiture",
    },
  },
  {
    id: 39,
    deliver_at: "2024-10-06 09:50",
    status: "waiting",
    location: "Antanimena Antananarivo",
    latitude: -18.9083,
    longitude: 47.5365,
    price: 13000,
    commission: 3500,
    comment: "Livraison en cours, client veut un suivi en temps réel.",
    product: {
      id: 14,
      name: "Enceinte portable",
      price: 13000,
      description: "Enceinte Bluetooth portable avec son puissant.",
      company: {
        id: 13,
        name: "SoundTech",
        phone_number: "034 98 123 45",
      },
    },
    client: {
      id: 13,
      name: "Nirina Raharison",
      phone_number: "0323214567",
      location: "Antanimena Antananarivo",
    },
    delivery_person: {
      id: 12,
      name: "Lova Andriamihaingo",
      phone_number: "0331237654",
    },
    vehicle: {
      id: 10,
      name: "Voiture Peugeot 208",
      type: "voiture",
    },
  },
  {
    id: 40,
    deliver_at: "2024-10-05 13:30",
    status: "delivered",
    location: "Ambatobe Antananarivo",
    latitude: -18.8971,
    longitude: 47.5452,
    price: 15000,
    commission: 4000,
    comment:
      "Client très content, à recommander pour les prochaines livraisons.",
    product: {
      id: 15,
      name: "Lampe de bureau LED",
      price: 15000,
      description: "Lampe de bureau LED avec réglage d'intensité.",
      company: {
        id: 14,
        name: "BureauTech",
        phone_number: "033 54 123 67",
      },
    },
    client: {
      id: 14,
      name: "Hery Rasolofonirina",
      phone_number: "0329876543",
      location: "Ambatobe Antananarivo",
    },
    delivery_person: {
      id: 13,
      name: "Jean Philippe",
      phone_number: "0341237654",
    },
    vehicle: {
      id: 8,
      name: "Vélo Électrique City Ride",
      type: "vélo",
    },
  },
];

export default deliveries;
