import DeliveryType from "@/types/delivery";

const deliveries: DeliveryType[] = [
  {
    id: 1,
    deliver_at: "2024-10-09",
    status: "delivered",
    location: "Analakely Antananarivo",
    latitude: -18.91368,
    longitude: 47.53613,
    price: 12000,
    commission: 3000,
    comment:
      "Client très satisfait, demande une nouvelle livraison quand son stock sera épuisé, il nous même donné plus de commission, hehe :)",
    product: {
      id: 1,
      name: "Cartable MSK",
      price: 12000,
      description:
        "A few screens from my ongoing project; List page and filters!",
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 1,
      name: "Tamby Roméo",
      phone_number: "0326798765",
      location: "Analakely Antananarivo",
    },
    delivery_person: {
      id: 1,
      name: "Jean Marc",
      phone_number: "0345467865",
    },
    vehicle: {
      id: 5,
      name: "Moto Honda 1234 TBD",
      type: "moto",
    },
  },
  {
    id: 2,
    deliver_at: "2024-10-10",
    status: "processing",
    location: "Ambatolampy Antananarivo",
    latitude: -19.3832,
    longitude: 47.4264,
    price: 15000,
    commission: 3500,
    product: {
      id: 2,
      name: "Sac à dos Adidas",
      description:
        "A few screens from my ongoing project; List page and filters!",
      price: 15000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 2,
      name: "Rina Sahondra",
      phone_number: "0346798765",
      location: "Ambatolampy Antananarivo",
    },
    delivery_person: {
      id: 2,
      name: "Patrick Rabe",
      phone_number: "0331234567",
    },
    vehicle: {
      id: 6,
      name: "Camion Toyota 5678 XYZ",
      type: "camion",
    },
  },
  {
    id: 3,
    deliver_at: "2024-10-11",
    status: "waiting",
    location: "Ivandry Antananarivo",
    latitude: -18.8942,
    longitude: 47.5256,
    price: 10000,
    commission: 2500,
    product: {
      id: 3,
      name: "T-shirt Nike",
      description:
        "A few screens from my ongoing project; List page and filters!",
      price: 10000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 3,
      name: "Aina Fidy",
      phone_number: "0321239876",
      location: "Ivandry Antananarivo",
    },
    delivery_person: {
      id: 3,
      name: "Rakoto Jean",
      phone_number: "0349876543",
    },
    vehicle: {
      id: 7,
      name: "Vélo Trek 4321 ZXC",
      type: "vélo",
    },
  },
  {
    id: 4,
    deliver_at: "2024-10-12",
    status: "to_deliver",
    location: "Tanjombato Antananarivo",
    latitude: -18.9291,
    longitude: 47.5315,
    price: 18000,
    commission: 4500,
    product: {
      id: 4,
      name: "Chaussures Puma",
      price: 18000,
      description:
        "A few screens from my ongoing project; List page and filters!",
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 4,
      name: "Haja Faniry",
      phone_number: "0337896543",
      location: "Tanjombato Antananarivo",
    },
    delivery_person: {
      id: 4,
      name: "Andry Hery",
      phone_number: "0324567890",
    },
    vehicle: {
      id: 8,
      name: "Scooter Piaggio 8765 DEF",
      type: "scooter",
    },
  },
  {
    id: 5,
    deliver_at: "2024-10-13",
    status: "canceled",
    location: "Ambohimanarina Antananarivo",
    latitude: -18.8726,
    longitude: 47.5381,
    price: 20000,
    commission: 5000,
    comment:
      "Le client a annulé sa commande à la derniere minute, à cause d’un retard de livraison",
    product: {
      id: 5,
      name: "Casquette Reebok",
      price: 20000,
      description:
        "A few screens from my ongoing project; List page and filters!",
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 5,
      name: "Hoby Rado",
      phone_number: "0343217654",
      location: "Ambohimanarina Antananarivo",
    },
    delivery_person: {
      id: 5,
      name: "Claude Lala",
      phone_number: "0338765432",
    },
    vehicle: {
      id: 9,
      name: "car Renault 1234 ABC",
      type: "car",
    },
  },
  {
    id: 6,
    deliver_at: "2024-10-14",
    status: "to_deliver",
    location: "Ankadifotsy Antananarivo",
    latitude: -18.9061,
    longitude: 47.5276,
    price: 22000,
    commission: 5500,
    product: {
      id: 6,
      name: "Montre Casio",
      price: 22000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 6,
      name: "Miora Sarah",
      phone_number: "0334567890",
      location: "Ankadifotsy Antananarivo",
    },
    delivery_person: {
      id: 6,
      name: "Faly Richard",
      phone_number: "0346543219",
    },
    vehicle: {
      id: 10,
      name: "Moto Yamaha 9876 GHJ",
      type: "moto",
    },
  },
  {
    id: 7,
    deliver_at: "2024-10-15",
    status: "waiting",
    location: "Ankorondrano Antananarivo",
    latitude: -18.8924,
    longitude: 47.5238,
    price: 30000,
    commission: 6000,
    product: {
      id: 7,
      name: "Ordinateur Portable HP",
      price: 30000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 7,
      name: "Joelina Hery",
      phone_number: "0329988776",
      location: "Ankorondrano Antananarivo",
    },
    delivery_person: {
      id: 7,
      name: "Mamy Gilbert",
      phone_number: "0347896543",
    },
    vehicle: {
      id: 11,
      name: "car Peugeot 5678 IJK",
      type: "car",
    },
  },
  {
    id: 8,
    deliver_at: "2024-10-16",
    status: "delivered",
    location: "Ambodivona Antananarivo",
    latitude: -18.9061,
    longitude: 47.5261,
    product: {
      id: 8,
      name: "Chaussures Nike Air",
      price: 17000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 8,
      name: "Lova Kevin",
      phone_number: "0331122334",
      location: "Ambodivona Antananarivo",
    },
    delivery_person: {
      id: 8,
      name: "Fetra Nambinina",
      phone_number: "0328765432",
    },
    vehicle: {
      id: 12,
      name: "Camion Iveco 9876 KLM",
      type: "camion",
    },
  },
  {
    id: 9,
    deliver_at: "2024-10-17",
    status: "canceled",
    location: "Ampefiloha Antananarivo",
    latitude: -18.9146,
    longitude: 47.5304,
    price: 25000,
    commission: 6250,
    comment:
      "Le client a annulé sa commande à la derniere minute, à cause d’un retard de livraison",
    product: {
      id: 9,
      name: "Lunettes Ray-Ban",
      price: 25000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 9,
      name: "Soa Fitah",
      phone_number: "0342233445",
      location: "Ampefiloha Antananarivo",
    },
    delivery_person: {
      id: 9,
      name: "Feno Micka",
      phone_number: "0334433221",
    },
    vehicle: {
      id: 13,
      name: "Scooter SYM 5432 NOP",
      type: "scooter",
    },
  },
  {
    id: 10,
    deliver_at: "2024-10-18",
    status: "processing",
    location: "Andraharo Antananarivo",
    latitude: -18.8792,
    longitude: 47.5247,
    price: 19000,
    commission: 4750,
    product: {
      id: 10,
      name: "Casque Bose",
      price: 19000,
      company: {
        id: 1,
        name: "Tambyy Corp.",
        phone_number: "036 78 876 90",
      },
    },
    client: {
      id: 10,
      name: "Mandresy Solofonirina",
      phone_number: "0326655443",
      location: "Andraharo Antananarivo",
    },
    delivery_person: {
      id: 10,
      name: "Mbola Hanitra",
      phone_number: "0346677889",
    },
    vehicle: {
      id: 14,
      name: "car Nissan 7654 QRS",
      type: "car",
    },
  },
  {
    id: 11,
    deliver_at: "2024-10-19",
    status: "to_deliver",
    location: "Antanimena Antananarivo",
    latitude: -18.9054,
    longitude: 47.5298,
    price: 21000,
    commission: 5250,
    product: {
      id: 11,
      name: "Clavier Logitech",
      price: 21000,
    },
    client: {
      id: 11,
      name: "Irina Rakoto",
      phone_number: "0341239876",
      location: "Antanimena Antananarivo",
    },
    delivery_person: {
      id: 11,
      name: "Dina Nono",
      phone_number: "0337766554",
    },
    vehicle: {
      id: 15,
      name: "Vélo Canyon 2345 TUV",
      type: "vélo",
    },
  },
  {
    id: 12,
    deliver_at: "2024-10-20",
    status: "delivered",
    location: "Anosibe Antananarivo",
    latitude: -18.9134,
    longitude: 47.4954,
    price: 28000,
    commission: 7000,
    product: {
      id: 12,
      name: "Chaise Gamer DXRacer",
      price: 28000,
    },
    client: {
      id: 12,
      name: "Hery Nomena",
      phone_number: "0325566778",
      location: "Anosibe Antananarivo",
    },
    delivery_person: {
      id: 12,
      name: "Rado Lalaina",
      phone_number: "0347890123",
    },
    vehicle: {
      id: 16,
      name: "car BMW 3456 XYZ",
      type: "car",
    },
  },
  {
    id: 13,
    deliver_at: "2024-10-18",
    status: "waiting",
    location: "Isoraka Antananarivo",
    latitude: -18.9067,
    longitude: 47.5205,
    price: 35000,
    commission: 8750,
    product: {
      id: 13,
      name: "Tablette Samsung",
      price: 35000,
    },
    client: {
      id: 13,
      name: "Faly Haja",
      phone_number: "0338877665",
      location: "Isoraka Antananarivo",
    },
    delivery_person: {
      id: 13,
      name: "Kanto Fetra",
      phone_number: "0349988776",
    },
    vehicle: {
      id: 17,
      name: "Moto Suzuki 6543 WXY",
      type: "moto",
    },
  },
  {
    id: 14,
    deliver_at: "2024-10-22",
    status: "processing",
    location: "Ambatomaro Antananarivo",
    latitude: -18.8874,
    longitude: 47.5481,
    price: 16000,
    commission: 4000,
    product: {
      id: 14,
      name: "Smartphone iPhone 13",
      price: 16000,
    },
    client: {
      id: 14,
      name: "Dera Liva",
      phone_number: "0323344556",
      location: "Ambatomaro Antananarivo",
    },
    delivery_person: {
      id: 14,
      name: "Tsiry Andry",
      phone_number: "0340987654",
    },
    vehicle: {
      id: 18,
      name: "Camion Mercedes 8765 UVW",
      type: "camion",
    },
  },
  {
    id: 15,
    deliver_at: "2024-10-23",
    status: "canceled",
    location: "Andoharanofotsy Antananarivo",
    latitude: -19.0086,
    longitude: 47.5435,
    price: 27000,
    commission: 6750,
    comment:
      "Le client a annulé sa commande à la derniere minute, à cause d’un retard de livraison",
    product: {
      id: 15,
      name: "Drone DJI Mavic Air",
      price: 27000,
    },
    client: {
      id: 15,
      name: "Rado Hery",
      phone_number: "0333322110",
      location: "Andoharanofotsy Antananarivo",
    },
    delivery_person: {
      id: 15,
      name: "Ando Jean",
      phone_number: "0325678901",
    },
    vehicle: {
      id: 19,
      name: "car Renault 9876 ABC",
      type: "car",
    },
  },
  {
    id: 16,
    deliver_at: "2024-10-23",
    status: "canceled",
    location: "Andoharanofotsy Antananarivo",
    latitude: -19.0086,
    longitude: 47.5435,
    price: 27000,
    commission: 6750,
    comment:
      "Le client a annulé sa commande à la derniere minute, à cause d’un retard de livraison",
    product: {
      id: 16,
      name: "Drone DJI Mavic Air",
      price: 27000,
    },
    client: {
      id: 16,
      name: "Rado Hery",
      phone_number: "0333322110",
      location: "Andoharanofotsy Antananarivo",
    },
    delivery_person: {
      id: 16,
      name: "Ando Jean",
      phone_number: "0325678901",
    },
    vehicle: {
      id: 19,
      name: "car Renault 9876 ABC",
      type: "car",
    },
  },
  {
    id: 17,
    deliver_at: "2024-10-24",
    status: "delivered",
    location: "Ivato Antananarivo",
    latitude: -18.7998,
    longitude: 47.4784,
    price: 30000,
    commission: 7500,
    comment: "La livraison a été effectuée avec succès.",
    product: {
      id: 17,
      name: "Laptop HP Pavilion",
      price: 30000,
    },
    client: {
      id: 17,
      name: "Tiana Ramiarison",
      phone_number: "0341234567",
      location: "Ivato Antananarivo",
    },
    delivery_person: {
      id: 17,
      name: "Nina Raharijaona",
      phone_number: "0323456789",
    },
    vehicle: {
      id: 20,
      name: "van Toyota 1234 XYZ",
      type: "van",
    },
  },
  {
    id: 18,
    deliver_at: "2024-10-25",
    status: "received_by_delivery_person",
    location: "Antananarivo",
    latitude: -18.8792,
    longitude: 47.5079,
    price: 15000,
    commission: 3750,
    comment: "En attente de confirmation du client.",
    product: {
      id: 18,
      name: "Smartphone Samsung Galaxy",
      price: 15000,
    },
    client: {
      id: 18,
      name: "Miora Andriamialy",
      phone_number: "0334455667",
      location: "Antananarivo",
    },
    delivery_person: {
      id: 18,
      name: "Rija Ravalomanana",
      phone_number: "0324567890",
    },
    vehicle: {
      id: 21,
      name: "motorcycle Yamaha 5678 DEF",
      type: "motorcycle",
    },
  },
  {
    id: 19,
    deliver_at: "2024-10-26",
    status: "delivered",
    location: "Mahamasina Antananarivo",
    latitude: -18.9111,
    longitude: 47.5296,
    price: 22000,
    commission: 5500,
    comment: "Livraison réussie au client.",
    product: {
      id: 19,
      name: "Camera Canon EOS",
      price: 22000,
    },
    client: {
      id: 19,
      name: "Fidy Andrianjafy",
      phone_number: "0345678901",
      location: "Mahamasina Antananarivo",
    },
    delivery_person: {
      id: 19,
      name: "Tovo Ranjato",
      phone_number: "0326789012",
    },
    vehicle: {
      id: 22,
      name: "truck Ford 9876 GHI",
      type: "truck",
    },
  },
  {
    id: 20,
    deliver_at: "2024-10-27",
    status: "waiting",
    location: "Antananarivo",
    latitude: -18.8792,
    longitude: 47.5079,
    price: 50000,
    commission: 12500,
    comment: "La livraison est en cours.",
    product: {
      id: 20,
      name: "TV LG 55 inches",
      price: 50000,
    },
    client: {
      id: 20,
      name: "Sitraka Harinjaka",
      phone_number: "0338765432",
      location: "Antananarivo",
    },
    delivery_person: {
      id: 20,
      name: "Bema Ravaloson",
      phone_number: "0327890123",
    },
    vehicle: {
      id: 23,
      name: "car Hyundai 6789 JKL",
      type: "car",
    },
  },
  {
    id: 21,
    deliver_at: "2024-10-28",
    status: "delivered",
    location: "Andohalo Antananarivo",
    latitude: -18.9265,
    longitude: 47.5233,
    price: 32000,
    commission: 8000,
    comment: "La livraison a été bien reçue.",
    product: {
      id: 21,
      name: "Tablet Apple iPad",
      price: 32000,
    },
    client: {
      id: 21,
      name: "Hery Ravaonjanahary",
      phone_number: "0349876543",
      location: "Andohalo Antananarivo",
    },
    delivery_person: {
      id: 21,
      name: "Tiana Mbola",
      phone_number: "0323456789",
    },
    vehicle: {
      id: 24,
      name: "van Mercedes 1234 OPQ",
      type: "van",
    },
  },
  {
    id: 22,
    deliver_at: "2024-10-29",
    status: "canceled",
    location: "Ankorondrano Antananarivo",
    latitude: -18.9199,
    longitude: 47.5272,
    price: 19000,
    commission: 4750,
    comment: "La livraison a échoué à cause d'une adresse incorrecte.",
    product: {
      id: 22,
      name: "Smartwatch Fitbit",
      price: 19000,
    },
    client: {
      id: 22,
      name: "Vola Rabemananjara",
      phone_number: "0336543210",
      location: "Ankorondrano Antananarivo",
    },
    delivery_person: {
      id: 22,
      name: "Andry Raketaka",
      phone_number: "0322345678",
    },
    vehicle: {
      id: 25,
      name: "motorcycle Honda 2345 QRS",
      type: "motorcycle",
    },
  },
  {
    id: 23,
    deliver_at: "2024-10-30",
    status: "delivered",
    location: "Analakely Antananarivo",
    latitude: -18.9265,
    longitude: 47.516,
    price: 35000,
    commission: 8750,
    comment: "Le client était très satisfait de la livraison.",
    product: {
      id: 23,
      name: "Printer Epson EcoTank",
      price: 35000,
    },
    client: {
      id: 23,
      name: "Rosa Andriamifidy",
      phone_number: "0341237890",
      location: "Analakely Antananarivo",
    },
    delivery_person: {
      id: 23,
      name: "Mika Andrianarivo",
      phone_number: "0325432109",
    },
    vehicle: {
      id: 26,
      name: "car Nissan 5432 TUV",
      type: "car",
    },
  },
  {
    id: 24,
    deliver_at: "2024-10-31",
    status: "received_by_delivery_person",
    location: "Tsaralalana Antananarivo",
    latitude: -18.9262,
    longitude: 47.5163,
    price: 45000,
    commission: 11250,
    comment: "En attente de confirmation du client.",
    product: {
      id: 24,
      name: "Speaker Bose",
      price: 45000,
    },
    client: {
      id: 24,
      name: "Sola Ravoahangy",
      phone_number: "0346789012",
      location: "Tsaralalana Antananarivo",
    },
    delivery_person: {
      id: 24,
      name: "Eliandro Raharijaona",
      phone_number: "0321234567",
    },
    vehicle: {
      id: 27,
      name: "van Fiat 8765 WXY",
      type: "van",
    },
  },
  {
    id: 25,
    deliver_at: "2024-11-01",
    status: "canceled",
    location: "Behoririka Antananarivo",
    latitude: -18.9265,
    longitude: 47.5133,
    price: 37000,
    commission: 9250,
    comment: "Le client a annulé sa commande à la derniere minute.",
    product: {
      id: 25,
      name: "Headphones Sony WH-1000XM4",
      price: 37000,
    },
    client: {
      id: 25,
      name: "Aina Ranjavola",
      phone_number: "0348765432",
      location: "Behoririka Antananarivo",
    },
    delivery_person: {
      id: 25,
      name: "Kanto Ravanantsoa",
      phone_number: "0324567890",
    },
    vehicle: {
      id: 28,
      name: "motorcycle Suzuki 4321 ABC",
      type: "motorcycle",
    },
  },
  {
    id: 26,
    deliver_at: "2024-10-02",
    status: "received_by_delivery_person",
    location: "Avaradoha Antananarivo",
    latitude: -18.9222,
    longitude: 47.5108,
    price: 21000,
    commission: 5250,
    comment: "La livraison est en cours.",
    product: {
      id: 26,
      name: "Bluetooth Speaker JBL",
      price: 21000,
    },
    client: {
      id: 26,
      name: "Rija Ramiarison",
      phone_number: "0341112233",
      location: "Avaradoha Antananarivo",
    },
    delivery_person: {
      id: 26,
      name: "Miora Rafaralahy",
      phone_number: "0323456789",
    },
    vehicle: {
      id: 29,
      name: "car Peugeot 1234 UVW",
      type: "car",
    },
  },
  {
    id: 27,
    deliver_at: "2024-11-03",
    status: "delivered",
    location: "Ankorondrano Antananarivo",
    latitude: -18.9211,
    longitude: 47.5226,
    price: 40000,
    commission: 10000,
    comment: "La livraison a été réussie.",
    product: {
      id: 27,
      name: "Game Console PlayStation 5",
      price: 40000,
    },
    client: {
      id: 27,
      name: "Mila Rakotoarisoa",
      phone_number: "0345678901",
      location: "Ankorondrano Antananarivo",
    },
    delivery_person: {
      id: 27,
      name: "Rina Rasoanaivo",
      phone_number: "0324567890",
    },
    vehicle: {
      id: 30,
      name: "van Renault 6789 STU",
      type: "van",
    },
  },
];

export default deliveries;
